# Generated by Django 5.1.7 on 2025-03-11 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('child_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('date_of_admission', models.DateField()),
                ('reason_for_admission', models.TextField()),
                ('medical_history', models.TextField(blank=True, null=True)),
                ('education_level', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, null=True)),
                ('guardian_email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('contact_info', models.EmailField(max_length=254)),
                ('date_of_joining', models.DateField()),
                ('qualifications', models.TextField()),
                ('emergency_contact', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
