# Generated by Django 5.1.7 on 2025-03-14 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='child_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
